sudo: false
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
script: "bundle exec rspec"
before_install:
  - gem update --system
  - gem --version
before_script:
  - bin/prepare-test.sh
